name: Robot Framework Tests

on: [push, workflow_dispatch]

jobs:
  test:
    name: Web tests 
    runs-on: ubuntu-24.04

    steps:
    - name: Clonar arquivos do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip  # Garantir que o pip esteja atualizado
        pip install -r requirements.txt

    - name: Executando os testes web
      run: |
        source venv/bin/activate  # Ativar novamente o ambiente virtual
        robot --outputdir results/ .

    - name: Test Repost
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-framework-report
        path: results

  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-24.04
    if: always()
    needs:
      - test

    permissions:
      contents: read
      pages: write
    environment:
      name: github-pages
      url: https://andre-min.github.io/ron_bugado_web/report.html
      
           
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: robot-framework-report
          path: results/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: results/

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
